sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - npm install -g bower
  - bower install

before_script:
  - gulp lint
  - travis_retry xvfb-run -s '-screen 0 1024x768x24' gulp perf:run
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || TRAVIS_BRANCH=quick/${TRAVIS_BUILD_ID} xvfb-run -s '-screen 0 1024x768x24' wct)

script:
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || gemini test test/visual)
  - xvfb-run -s '-screen 0 1024x768x24' wct
